package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
	"github.com/finsight-org/finsight/internal/wealthsimple/generated"
	"github.com/finsight-org/finsight/internal/wealthsimple/model"
)

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) (*model.AccountsResult, error) {
	cache := ctx.Value(accountsKey{}).(*accountCache)
	cache.once.Do(func() {
		cache.result, cache.err = cache.client.Accounts(ctx)
	})
	if cache.err != nil && len(cache.result.Accounts) == 0 {
		return nil, cache.err
	}
	if cache.err != nil {
		graphql.AddError(ctx, cache.err)
	}
	result := &model.AccountsResult{Accounts: make([]*model.Account, 0, len(cache.result.Accounts)), Warnings: make([]*model.Warning, 0, len(cache.result.Warnings))}
	for _, account := range cache.result.Accounts {
		converted := &model.Account{ID: account.ID, Name: account.Name, Type: account.Type, Currency: account.Currency, BalanceKind: account.BalanceKind}
		if account.Balance != nil {
			converted.Balance = &model.Money{Amount: account.Balance.Amount, Currency: account.Balance.Currency}
		}
		result.Accounts = append(result.Accounts, converted)
	}
	for _, warning := range cache.result.Warnings {
		converted := &model.Warning{Code: warning.Code, Message: warning.Message}
		if warning.AccountID != "" {
			converted.AccountID = &warning.AccountID
		}
		result.Warnings = append(result.Warnings, converted)
	}
	return result, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
