// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/finsight-org/finsight/internal/gateway/jsonvalue"
)

type ConnectedProvider struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProviderQueryError struct {
	Message    string          `json:"message"`
	Path       *jsonvalue.JSON `json:"path,omitempty"`
	Extensions *jsonvalue.JSON `json:"extensions,omitempty"`
}

type ProviderQueryResponse struct {
	Data   *jsonvalue.JSON       `json:"data,omitempty"`
	Errors []*ProviderQueryError `json:"errors"`
}

type Query struct {
}
