// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/finsight-org/finsight/internal/wealthsimple"
)

type Account struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Type        string `json:"type"`
	Currency    string `json:"currency"`
	BalanceKind string `json:"balanceKind"`
	Balance     *Money `json:"balance,omitempty"`
}

type AccountsResult struct {
	Accounts []*Account `json:"accounts"`
	Warnings []*Warning `json:"warnings"`
}

// A decimal balance with the currency reported by Wealthsimple.
type Money struct {
	Amount   wealthsimple.Decimal `json:"amount"`
	Currency string               `json:"currency"`
}

// Open Wealthsimple accounts. Investment and cash balances are net liquidation value, not buying power or available cash. Credit card balances are amount owed. A missing balance is null; values are not converted or summed.
type Query struct {
}

type Warning struct {
	AccountID *string `json:"accountId,omitempty"`
	Code      string  `json:"code"`
	Message   string  `json:"message"`
}
