package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"bytes"
	"context"
	"encoding/json"

	"github.com/finsight-org/finsight/internal/gateway/generated"
	"github.com/finsight-org/finsight/internal/gateway/jsonvalue"
	"github.com/finsight-org/finsight/internal/gateway/model"
	"github.com/finsight-org/finsight/internal/providergraphql"
	"github.com/finsight-org/finsight/internal/wealthsimple"
)

// ConnectedProviders is the resolver for the connectedProviders field.
func (r *queryResolver) ConnectedProviders(ctx context.Context) ([]*model.ConnectedProvider, error) {
	if r.Connected != nil && r.Connected() {
		return []*model.ConnectedProvider{{ID: "wealthsimple", Name: "Wealthsimple"}}, nil
	}
	return []*model.ConnectedProvider{}, nil
}

// ProviderSchema is the resolver for the providerSchema field.
func (r *queryResolver) ProviderSchema(ctx context.Context, provider string) (string, error) {
	if provider != "wealthsimple" {
		return "", gatewayError("PROVIDER_NOT_FOUND", "Provider is not registered.")
	}
	return wealthsimple.ProviderSchema, nil
}

// ExecuteProviderQuery is the resolver for the executeProviderQuery field.
func (r *queryResolver) ExecuteProviderQuery(ctx context.Context, provider string, query string, variables *jsonvalue.JSON, operationName *string) (*model.ProviderQueryResponse, error) {
	if provider != "wealthsimple" {
		return nil, gatewayError("PROVIDER_NOT_FOUND", "Provider is not registered.")
	}
	if len(query) > 64<<10 {
		return nil, gatewayError("QUERY_TOO_LARGE", "Provider GraphQL query is too large.")
	}
	if r.Client == nil {
		return nil, gatewayError("PROVIDER_NOT_CONNECTED", "Provider is not connected.")
	}
	client, err := r.Client(ctx)
	if err != nil {
		return nil, gatewayError("PROVIDER_NOT_CONNECTED", "Provider is not connected.")
	}
	name := ""
	if operationName != nil {
		name = *operationName
	}
	var vars map[string]any
	if variables != nil {
		var ok bool
		vars, ok = variables.Value.(map[string]any)
		if !ok {
			return nil, gatewayError("INVALID_VARIABLES", "Variables must be a JSON object.")
		}
	}
	data, issues, err := providergraphql.Execute(ctx, client, query, vars, name)
	if valid, ok := client.(interface{ Valid() bool }); ok && !valid.Valid() {
		hasReconnect := false
		for _, issue := range issues {
			if ext, ok := issue["extensions"].(map[string]any); ok && ext["code"] == "RECONNECT_REQUIRED" {
				hasReconnect = true
			}
		}
		if !hasReconnect {
			return nil, gatewayError("RECONNECT_REQUIRED", "Wealthsimple connection changed while the query was running.")
		}
	}
	if err != nil {
		return nil, gatewayError("PROVIDER_QUERY_FAILED", "Provider query could not be completed.")
	}
	var value map[string]any
	if len(data) > 0 && string(data) != "null" {
		decoder := json.NewDecoder(bytes.NewReader(data))
		decoder.UseNumber()
		if decoder.Decode(&value) != nil {
			return nil, gatewayError("PROVIDER_QUERY_FAILED", "Provider query could not be completed.")
		}
	}
	response := &model.ProviderQueryResponse{Data: &jsonvalue.JSON{Value: value}, Errors: make([]*model.ProviderQueryError, 0, len(issues))}
	for _, issue := range issues {
		entry := &model.ProviderQueryError{Message: "Provider query could not be completed."}
		if message, ok := issue["message"].(string); ok {
			entry.Message = message
		}
		if path, ok := issue["path"]; ok {
			entry.Path = &jsonvalue.JSON{Value: path}
		}
		if extensions, ok := issue["extensions"].(map[string]any); ok {
			entry.Extensions = &jsonvalue.JSON{Value: extensions}
		}
		response.Errors = append(response.Errors, entry)
	}
	return response, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
